[project]
name = "projeto-analise-dados"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasus-dbc>=0.1.3",
    "dbfread>=2.0.7",
    "pandas>=2.3.3",
    "pyodbc>=5.3.0",
]
